### ISSUE TITLE
MAINTAINERS file vs. - maintainers in yaml

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/metainvenio#9]
Is there a way to support both MAINTAINERS file if it is present and maintainers list in yaml otherwise?

**Comment by lnielsen** [comment]
The idea is that the YAML file is the ground truth. MetaInvenio then takes care of writing the ``MAINTAINERS`` file in the repo (see https://github.com/inveniosoftware/metainvenio/blob/master/metainvenio/github.py#L263)

**Comment by lnielsen** [comment]
Also the ``yaml-template`` (https://github.com/inveniosoftware/metainvenio/blob/master/metainvenio/github.py#L353) will read the MAINTAINERS file to get you started.
